// Generated by `wit-bindgen` 0.11.0. DO NOT EDIT!
#ifndef __BINDINGS_POLL_H
#define __BINDINGS_POLL_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  char*ptr;
  size_t len;
} poll_string_t;

typedef struct {
  poll_string_t f0;
  poll_string_t f1;
} poll_tuple2_string_string_t;

typedef struct {
  poll_tuple2_string_string_t *ptr;
  size_t len;
} poll_list_tuple2_string_string_t;

typedef struct {
  poll_string_t *ptr;
  size_t len;
} poll_list_string_t;

typedef struct {
  bool is_some;
  poll_string_t val;
} poll_option_string_t;

typedef struct {
  uint32_t *ptr;
  size_t len;
} poll_list_u32_t;

typedef struct {
  poll_string_t user_token;
  poll_list_u32_t answers;
} ilhan_golem_poll_api_response_creation_t;

typedef struct {
  poll_string_t text;
  poll_list_string_t answers;
} ilhan_golem_poll_api_question_t;

typedef struct {
  ilhan_golem_poll_api_question_t *ptr;
  size_t len;
} poll_list_ilhan_golem_poll_api_question_t;

typedef struct {
  poll_string_t owner_email;
  poll_string_t title;
  int64_t end;
  poll_list_ilhan_golem_poll_api_question_t questions;
} ilhan_golem_poll_api_poll_t;

typedef struct {
  poll_string_t user;
  poll_list_u32_t answers;
} ilhan_golem_poll_api_response_t;

typedef struct {
  ilhan_golem_poll_api_response_t *ptr;
  size_t len;
} poll_list_ilhan_golem_poll_api_response_t;

typedef struct {
  ilhan_golem_poll_api_poll_t poll;
  bool open;
  poll_list_ilhan_golem_poll_api_response_t responses;
} ilhan_golem_poll_api_poll_data_t;

typedef struct {
  bool is_err;
  union {
    ilhan_golem_poll_api_poll_t ok;
    poll_string_t err;
  } val;
} poll_result_ilhan_golem_poll_api_poll_string_t;

typedef struct {
  bool is_err;
  union {
    poll_string_t err;
  } val;
} poll_result_void_string_t;

typedef struct {
  bool is_err;
  union {
    ilhan_golem_poll_api_poll_data_t ok;
    poll_string_t err;
  } val;
} poll_result_ilhan_golem_poll_api_poll_data_string_t;

// Imported Functions from `wasi:cli/environment`
// Get the POSIX-style environment variables.
// 
// Each environment variable is provided as a pair of string variable names
// and string value.
// 
// Morally, these are a value import, but until value imports are available
// in the component model, this import function should return the same
// values each time it is called.
void wasi_cli_environment_get_environment(poll_list_tuple2_string_string_t *ret);
// Get the POSIX-style arguments to the program.
void wasi_cli_environment_get_arguments(poll_list_string_t *ret);
// Return a path that programs should use as their initial current working
// directory, interpreting `.` as shorthand for this.
void wasi_cli_environment_initial_cwd(poll_option_string_t *ret);

// Exported Functions from `ilhan:golem-poll/api`
void exports_ilhan_golem_poll_api_create(ilhan_golem_poll_api_poll_t *poll_data, poll_result_ilhan_golem_poll_api_poll_string_t *ret);
void exports_ilhan_golem_poll_api_respond(ilhan_golem_poll_api_response_creation_t *answer, poll_result_void_string_t *ret);
void exports_ilhan_golem_poll_api_get(poll_string_t *access_token, poll_result_ilhan_golem_poll_api_poll_data_string_t *ret);
void exports_ilhan_golem_poll_api_close(poll_string_t *access_token, poll_result_void_string_t *ret);
void exports_ilhan_golem_poll_api_delete(poll_string_t *access_token, poll_result_void_string_t *ret);

// Helper Functions

void poll_tuple2_string_string_free(poll_tuple2_string_string_t *ptr);
void poll_list_tuple2_string_string_free(poll_list_tuple2_string_string_t *ptr);
void poll_list_string_free(poll_list_string_t *ptr);
void poll_option_string_free(poll_option_string_t *ptr);
void poll_list_u32_free(poll_list_u32_t *ptr);
void ilhan_golem_poll_api_response_creation_free(ilhan_golem_poll_api_response_creation_t *ptr);
void ilhan_golem_poll_api_question_free(ilhan_golem_poll_api_question_t *ptr);
void poll_list_ilhan_golem_poll_api_question_free(poll_list_ilhan_golem_poll_api_question_t *ptr);
void ilhan_golem_poll_api_poll_free(ilhan_golem_poll_api_poll_t *ptr);
void ilhan_golem_poll_api_response_free(ilhan_golem_poll_api_response_t *ptr);
void poll_list_ilhan_golem_poll_api_response_free(poll_list_ilhan_golem_poll_api_response_t *ptr);
void ilhan_golem_poll_api_poll_data_free(ilhan_golem_poll_api_poll_data_t *ptr);
void poll_result_ilhan_golem_poll_api_poll_string_free(poll_result_ilhan_golem_poll_api_poll_string_t *ptr);
void poll_result_void_string_free(poll_result_void_string_t *ptr);
void poll_result_ilhan_golem_poll_api_poll_data_string_free(poll_result_ilhan_golem_poll_api_poll_data_string_t *ptr);
void poll_string_set(poll_string_t *ret, const char*s);
void poll_string_dup(poll_string_t *ret, const char*s);
void poll_string_free(poll_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
