// Generated by `wit-bindgen` 0.11.0. DO NOT EDIT!
#include "poll.h"


__attribute__((__import_module__("wasi:cli/environment"), __import_name__("get-environment")))
void __wasm_import_wasi_cli_environment_get_environment(int32_t);

__attribute__((__import_module__("wasi:cli/environment"), __import_name__("get-arguments")))
void __wasm_import_wasi_cli_environment_get_arguments(int32_t);

__attribute__((__import_module__("wasi:cli/environment"), __import_name__("initial-cwd")))
void __wasm_import_wasi_cli_environment_initial_cwd(int32_t);
__attribute__((__weak__, __export_name__("cabi_post_ilhan:golem-poll/api#create")))
void __wasm_export_exports_ilhan_golem_poll_api_create_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      if ((*((int32_t*) (arg0 + 12))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 8))));
      }
      if ((*((int32_t*) (arg0 + 20))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 16))));
      }
      int32_t ptr0 = *((int32_t*) (arg0 + 32));
      int32_t len1 = *((int32_t*) (arg0 + 36));
      for (int32_t i2 = 0; i2 < len1; i2++) {
        int32_t base = ptr0 + i2 * 16;
        (void) base;
        if ((*((int32_t*) (base + 4))) > 0) {
          free((void*) (*((int32_t*) (base + 0))));
        }
        int32_t ptr = *((int32_t*) (base + 8));
        int32_t len = *((int32_t*) (base + 12));
        for (int32_t i = 0; i < len; i++) {
          int32_t base = ptr + i * 8;
          (void) base;
          if ((*((int32_t*) (base + 4))) > 0) {
            free((void*) (*((int32_t*) (base + 0))));
          }
        }
        if (len > 0) {
          free((void*) (ptr));
        }
      }
      if (len1 > 0) {
        free((void*) (ptr0));
      }
      break;
    }
    case 1: {
      if ((*((int32_t*) (arg0 + 12))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 8))));
      }
      break;
    }
  }
}
__attribute__((__weak__, __export_name__("cabi_post_ilhan:golem-poll/api#respond")))
void __wasm_export_exports_ilhan_golem_poll_api_respond_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
  }
}
__attribute__((__weak__, __export_name__("cabi_post_ilhan:golem-poll/api#get")))
void __wasm_export_exports_ilhan_golem_poll_api_get_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      if ((*((int32_t*) (arg0 + 12))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 8))));
      }
      if ((*((int32_t*) (arg0 + 20))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 16))));
      }
      int32_t ptr0 = *((int32_t*) (arg0 + 32));
      int32_t len1 = *((int32_t*) (arg0 + 36));
      for (int32_t i2 = 0; i2 < len1; i2++) {
        int32_t base = ptr0 + i2 * 16;
        (void) base;
        if ((*((int32_t*) (base + 4))) > 0) {
          free((void*) (*((int32_t*) (base + 0))));
        }
        int32_t ptr = *((int32_t*) (base + 8));
        int32_t len = *((int32_t*) (base + 12));
        for (int32_t i = 0; i < len; i++) {
          int32_t base = ptr + i * 8;
          (void) base;
          if ((*((int32_t*) (base + 4))) > 0) {
            free((void*) (*((int32_t*) (base + 0))));
          }
        }
        if (len > 0) {
          free((void*) (ptr));
        }
      }
      if (len1 > 0) {
        free((void*) (ptr0));
      }
      int32_t ptr6 = *((int32_t*) (arg0 + 44));
      int32_t len7 = *((int32_t*) (arg0 + 48));
      for (int32_t i8 = 0; i8 < len7; i8++) {
        int32_t base = ptr6 + i8 * 16;
        (void) base;
        if ((*((int32_t*) (base + 4))) > 0) {
          free((void*) (*((int32_t*) (base + 0))));
        }
        int32_t ptr3 = *((int32_t*) (base + 8));
        int32_t len4 = *((int32_t*) (base + 12));
        for (int32_t i5 = 0; i5 < len4; i5++) {
          int32_t base = ptr3 + i5 * 4;
          (void) base;
        }
        if (len4 > 0) {
          free((void*) (ptr3));
        }
      }
      if (len7 > 0) {
        free((void*) (ptr6));
      }
      break;
    }
    case 1: {
      if ((*((int32_t*) (arg0 + 12))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 8))));
      }
      break;
    }
  }
}
__attribute__((__weak__, __export_name__("cabi_post_ilhan:golem-poll/api#close")))
void __wasm_export_exports_ilhan_golem_poll_api_close_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
  }
}
__attribute__((__weak__, __export_name__("cabi_post_ilhan:golem-poll/api#delete")))
void __wasm_export_exports_ilhan_golem_poll_api_delete_post_return(int32_t arg0) {
  switch ((int32_t) (int32_t) (*((uint8_t*) (arg0 + 0)))) {
    case 0: {
      break;
    }
    case 1: {
      if ((*((int32_t*) (arg0 + 8))) > 0) {
        free((void*) (*((int32_t*) (arg0 + 4))));
      }
      break;
    }
  }
}

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void poll_tuple2_string_string_free(poll_tuple2_string_string_t *ptr) {
  poll_string_free(&ptr->f0);
  poll_string_free(&ptr->f1);
}

void poll_list_tuple2_string_string_free(poll_list_tuple2_string_string_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    poll_tuple2_string_string_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void poll_list_string_free(poll_list_string_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    poll_string_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void poll_option_string_free(poll_option_string_t *ptr) {
  if (ptr->is_some) {
    poll_string_free(&ptr->val);
  }
}

void poll_list_u32_free(poll_list_u32_t *ptr) {
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void ilhan_golem_poll_api_response_creation_free(ilhan_golem_poll_api_response_creation_t *ptr) {
  poll_string_free(&ptr->user_token);
  poll_list_u32_free(&ptr->answers);
}

void ilhan_golem_poll_api_question_free(ilhan_golem_poll_api_question_t *ptr) {
  poll_string_free(&ptr->text);
  poll_list_string_free(&ptr->answers);
}

void poll_list_ilhan_golem_poll_api_question_free(poll_list_ilhan_golem_poll_api_question_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    ilhan_golem_poll_api_question_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void ilhan_golem_poll_api_poll_free(ilhan_golem_poll_api_poll_t *ptr) {
  poll_string_free(&ptr->owner_email);
  poll_string_free(&ptr->title);
  poll_list_ilhan_golem_poll_api_question_free(&ptr->questions);
}

void ilhan_golem_poll_api_response_free(ilhan_golem_poll_api_response_t *ptr) {
  poll_string_free(&ptr->user);
  poll_list_u32_free(&ptr->answers);
}

void poll_list_ilhan_golem_poll_api_response_free(poll_list_ilhan_golem_poll_api_response_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
    ilhan_golem_poll_api_response_free(&ptr->ptr[i]);
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void ilhan_golem_poll_api_poll_data_free(ilhan_golem_poll_api_poll_data_t *ptr) {
  ilhan_golem_poll_api_poll_free(&ptr->poll);
  poll_list_ilhan_golem_poll_api_response_free(&ptr->responses);
}

void poll_result_ilhan_golem_poll_api_poll_string_free(poll_result_ilhan_golem_poll_api_poll_string_t *ptr) {
  if (!ptr->is_err) {
    ilhan_golem_poll_api_poll_free(&ptr->val.ok);
  } else {
    poll_string_free(&ptr->val.err);
  }
}

void poll_result_void_string_free(poll_result_void_string_t *ptr) {
  if (!ptr->is_err) {
  } else {
    poll_string_free(&ptr->val.err);
  }
}

void poll_result_ilhan_golem_poll_api_poll_data_string_free(poll_result_ilhan_golem_poll_api_poll_data_string_t *ptr) {
  if (!ptr->is_err) {
    ilhan_golem_poll_api_poll_data_free(&ptr->val.ok);
  } else {
    poll_string_free(&ptr->val.err);
  }
}

void poll_string_set(poll_string_t *ret, const char*s) {
  ret->ptr = (char*) s;
  ret->len = strlen(s);
}

void poll_string_dup(poll_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void poll_string_free(poll_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__aligned__(8)))
static uint8_t RET_AREA[56];

void wasi_cli_environment_get_environment(poll_list_tuple2_string_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_cli_environment_get_environment(ptr);
  *ret = (poll_list_tuple2_string_string_t) { (poll_tuple2_string_string_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wasi_cli_environment_get_arguments(poll_list_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_cli_environment_get_arguments(ptr);
  *ret = (poll_list_string_t) { (poll_string_t*)(*((int32_t*) (ptr + 0))), (size_t)(*((int32_t*) (ptr + 4))) };
}

void wasi_cli_environment_initial_cwd(poll_option_string_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_wasi_cli_environment_initial_cwd(ptr);
  poll_option_string_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (poll_string_t) { (char*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
  }
  *ret = option;
}

__attribute__((__export_name__("ilhan:golem-poll/api#create")))
int32_t __wasm_export_exports_ilhan_golem_poll_api_create(int32_t arg, int32_t arg0, int32_t arg1, int32_t arg2, int64_t arg3, int32_t arg4, int32_t arg5) {
  ilhan_golem_poll_api_poll_t arg6 = (ilhan_golem_poll_api_poll_t) {
    (poll_string_t) { (char*)(arg), (size_t)(arg0) },
    (poll_string_t) { (char*)(arg1), (size_t)(arg2) },
    arg3,
    (poll_list_ilhan_golem_poll_api_question_t) { (ilhan_golem_poll_api_question_t*)(arg4), (size_t)(arg5) },
  };
  poll_result_ilhan_golem_poll_api_poll_string_t ret;
  exports_ilhan_golem_poll_api_create(&arg6, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  if ((ret).is_err) {
    const poll_string_t *payload7 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 12)) = (int32_t) (*payload7).len;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload7).ptr;
  } else {
    const ilhan_golem_poll_api_poll_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + 12)) = (int32_t) ((*payload).owner_email).len;
    *((int32_t*)(ptr + 8)) = (int32_t) ((*payload).owner_email).ptr;
    *((int32_t*)(ptr + 20)) = (int32_t) ((*payload).title).len;
    *((int32_t*)(ptr + 16)) = (int32_t) ((*payload).title).ptr;
    *((int64_t*)(ptr + 24)) = (*payload).end;
    *((int32_t*)(ptr + 36)) = (int32_t) ((*payload).questions).len;
    *((int32_t*)(ptr + 32)) = (int32_t) ((*payload).questions).ptr;
  }
  return ptr;
}

__attribute__((__export_name__("ilhan:golem-poll/api#respond")))
int32_t __wasm_export_exports_ilhan_golem_poll_api_respond(int32_t arg, int32_t arg0, int32_t arg1, int32_t arg2) {
  ilhan_golem_poll_api_response_creation_t arg3 = (ilhan_golem_poll_api_response_creation_t) {
    (poll_string_t) { (char*)(arg), (size_t)(arg0) },
    (poll_list_u32_t) { (uint32_t*)(arg1), (size_t)(arg2) },
  };
  poll_result_void_string_t ret;
  exports_ilhan_golem_poll_api_respond(&arg3, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  if ((ret).is_err) {
    const poll_string_t *payload4 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload4).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload4).ptr;
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

__attribute__((__export_name__("ilhan:golem-poll/api#get")))
int32_t __wasm_export_exports_ilhan_golem_poll_api_get(int32_t arg, int32_t arg0) {
  poll_string_t arg1 = (poll_string_t) { (char*)(arg), (size_t)(arg0) };
  poll_result_ilhan_golem_poll_api_poll_data_string_t ret;
  exports_ilhan_golem_poll_api_get(&arg1, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  if ((ret).is_err) {
    const poll_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 12)) = (int32_t) (*payload2).len;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload2).ptr;
  } else {
    const ilhan_golem_poll_api_poll_data_t *payload = &(ret).val.ok;*((int8_t*)(ptr + 0)) = 0;
    *((int32_t*)(ptr + 12)) = (int32_t) (((*payload).poll).owner_email).len;
    *((int32_t*)(ptr + 8)) = (int32_t) (((*payload).poll).owner_email).ptr;
    *((int32_t*)(ptr + 20)) = (int32_t) (((*payload).poll).title).len;
    *((int32_t*)(ptr + 16)) = (int32_t) (((*payload).poll).title).ptr;
    *((int64_t*)(ptr + 24)) = ((*payload).poll).end;
    *((int32_t*)(ptr + 36)) = (int32_t) (((*payload).poll).questions).len;
    *((int32_t*)(ptr + 32)) = (int32_t) (((*payload).poll).questions).ptr;
    *((int8_t*)(ptr + 40)) = (*payload).open;
    *((int32_t*)(ptr + 48)) = (int32_t) ((*payload).responses).len;
    *((int32_t*)(ptr + 44)) = (int32_t) ((*payload).responses).ptr;
  }
  return ptr;
}

__attribute__((__export_name__("ilhan:golem-poll/api#close")))
int32_t __wasm_export_exports_ilhan_golem_poll_api_close(int32_t arg, int32_t arg0) {
  poll_string_t arg1 = (poll_string_t) { (char*)(arg), (size_t)(arg0) };
  poll_result_void_string_t ret;
  exports_ilhan_golem_poll_api_close(&arg1, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  if ((ret).is_err) {
    const poll_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload2).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload2).ptr;
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

__attribute__((__export_name__("ilhan:golem-poll/api#delete")))
int32_t __wasm_export_exports_ilhan_golem_poll_api_delete(int32_t arg, int32_t arg0) {
  poll_string_t arg1 = (poll_string_t) { (char*)(arg), (size_t)(arg0) };
  poll_result_void_string_t ret;
  exports_ilhan_golem_poll_api_delete(&arg1, &ret);
  int32_t ptr = (int32_t) &RET_AREA;
  if ((ret).is_err) {
    const poll_string_t *payload2 = &(ret).val.err;*((int8_t*)(ptr + 0)) = 1;
    *((int32_t*)(ptr + 8)) = (int32_t) (*payload2).len;
    *((int32_t*)(ptr + 4)) = (int32_t) (*payload2).ptr;
  } else {
    *((int8_t*)(ptr + 0)) = 0;
  }
  return ptr;
}

extern void __component_type_object_force_link_poll(void);
void __component_type_object_force_link_poll_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_poll();
}
